os:
  - linux
  - osx

language: ruby
rvm:
  - 2.4
  - 2.7
  - jruby

before_install:
  # Using a recent version of bundler in order to avoid gem installation errors
  - gem install bundler -v 1.15.4

script: bundle exec rake report_builder:test_everything
