version: '1.0.{build}'

environment:
  matrix:
    - RUBY_VERSION: 27
    - RUBY_VERSION: 27-x64
    - RUBY_VERSION: 31

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake report_builder:test_everything
